// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqcfeayzcfjfzdfupqax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxY2ZlYXl6Y2ZqZnpkZnVwcWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTg5NjEsImV4cCI6MjA3MjQ3NDk2MX0.iH_CmumyB_fejVW945-3V_Pv57zZU9sl5J0ZEXQnkkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});